---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bWFzdGVy
  mongo-root-password: aGFsd2E=
  mongo-express-username: YWRtaW4=
  mongo-express-password: cGFzcw==
